### ISSUE TITLE
Unable to copy autodrive_simulator.sh to /home/autodrive_simulator.sh

### ISSUE THREAD

**Issue by chenyenru** [AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing#1]
@Tinker-Twins 
I tried building docker image with the following command:

```bash
docker build --tag autodriveecosystem/autodrive_f1tenth_sim:v2024.1 -f autodrive_simulator.Dockerfile .
```

However, the following error is returned:

```bash
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/autodrive_simulator.sh": permission denied: unknown.
```

It seems like `COPY autodrive_simulator.sh /home` in the Dockerfile didn't work. Wondering if there's any work around?

**Comment by Tinker-Twins** [comment]
Hey @chenyenru,

The error you have encountered does not seem to be related to the `COPY` operation. It looks like the entrypoint shell script `autodrive_simulator.sh` does not have executable rights.

You can use the following command to grant executable rights to all shell scripts before building the container:
```bash
sudo chmod +x *.sh
```

Thanks and cheers,
Tinker Twins
