### ISSUE TITLE
Reset the simulator through the bridge

### ISSUE THREAD

**Issue by hodriozola** [AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing#7]
Dear all,

We are using AutoDRIVE's F1Tenth simulation environment to validate our autonomous driving algorithm. For the learning and validation process, we need to reset the environment in the same way as when you press the "Reset" button on the UI. Is there any way to send a command through the bridge for this purpose?

Thanks for your attention.

Best regards.

**Comment by Tinker-Twins** [comment]
Thanks for your suggestion!

We have updated AutoDRIVE Simulator and AutoDRIVE Devkit to include a soft reset functionality that you can use via the API to reset the simulation to initial conditions (without disconnecting the API).

Please pull the latest container images (or re-download the local versions) for the simulator and devkit to get this working.
You can reset the simulation by publishing a Boolean (True) message on the topic `/autodrive/reset_command`. However, do not forget to set it to False again or else the simulation will keep resetting. Please also note that the `/autodrive/reset_command` topic is a restricted topic and can only be used offline (e.g., for training RL policies). This topic should not be accessed for racing autonomously during runtime (in the solutions that you submit), doing so could result in the team's disqualification from the competition.

Hope this helps and all the best for the competition ahead!
