### ISSUE TITLE
Lag and Errors in Rviz After a Few Minutes of Running on the Autodrive Devkit

### ISSUE THREAD

**Issue by Beaver6513** [AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing#8]
Hi, I'm working with the Autodrive ecosystem for the F1TENTH competition and I'm experiencing an issue with the devkit. I have a high-performance PC, but after about a minute or two, I start noticing significant lag in Rviz, with the messages not updating smoothly. This lag leads to errors in the autonomous navigation algorithms.

I ran the "docker stats" command and noticed that the memory usage of the container running the devkit keeps increasing over time. This memory consumption seems to be the cause of the lag and errors.

I've also verified that the issue is not related to my code, as I experience the same problem even when running only the simulator and the devkit, without any additional custom code.

Has anyone else encountered this issue? If so, do you have any suggestions or solutions to resolve it? I've already searched online but couldn't find any relevant information. Additionally, I tried running the setup on another machine, but the issue persists.
![lag_issue](https://github.com/user-attachments/assets/d05f892b-a268-483e-a308-4ed015214155)

As You can see the simulation still runs properly while only the bridge and the ros messages are laggign
Any help would be greatly appreciated!

**Comment by kartman88** [comment]
I'm facing the same issue. I have an hig-performance PC too but the bridge is still lagging

**Comment by Tinker-Twins** [comment]
Thanks for your feedback!

We have updated AutoDRIVE Simulator as well as AutoDRIVE Devkit to optimize the communication bridge as well as ROS 2 node infrastructure for facilitating faster communication. Please pull the latest container images (or re-download the local versions) for the simulator and devkit to get this working.

Hope this helps and all the best for the competition ahead!
